apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    version: green   # Jenkins will update to green
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer